ALTER TABLE portfolio_settings
    ADD COLUMN IF NOT EXISTS project_grid_columns TEXT NOT NULL DEFAULT 'TWO',
    ADD COLUMN IF NOT EXISTS project_card_style TEXT NOT NULL DEFAULT 'STANDARD',
    ADD COLUMN IF NOT EXISTS typography_scale TEXT NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS hero_style TEXT NOT NULL DEFAULT 'GRADIENT',
    ADD COLUMN IF NOT EXISTS navigation_style TEXT NOT NULL DEFAULT 'TOP',
    ADD COLUMN IF NOT EXISTS animation_level TEXT NOT NULL DEFAULT 'SUBTLE';

ALTER TABLE contact_profiles
    ADD COLUMN IF NOT EXISTS og_image_url TEXT,
    ADD COLUMN IF NOT EXISTS favicon_url TEXT;
