ALTER TABLE resume_settings
    ADD COLUMN IF NOT EXISTS section_spacing TEXT NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS item_spacing TEXT NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS description_style TEXT NOT NULL DEFAULT 'BULLETS',
    ADD COLUMN IF NOT EXISTS bullet_char TEXT NOT NULL DEFAULT 'DOT',
    ADD COLUMN IF NOT EXISTS item_title_emphasis TEXT NOT NULL DEFAULT 'TITLE',
    ADD COLUMN IF NOT EXISTS highlight_current_role BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS location_display TEXT NOT NULL DEFAULT 'OWN_LINE',
    ADD COLUMN IF NOT EXISTS heading_font_family TEXT NOT NULL DEFAULT 'SANS',
    ADD COLUMN IF NOT EXISTS body_font_family TEXT NOT NULL DEFAULT 'SANS',
    ADD COLUMN IF NOT EXISTS name_font_weight TEXT NOT NULL DEFAULT 'SEMIBOLD',
    ADD COLUMN IF NOT EXISTS section_title_font_weight TEXT NOT NULL DEFAULT 'SEMIBOLD',
    ADD COLUMN IF NOT EXISTS line_height TEXT NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS heading_letter_spacing TEXT NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS section_title_small_caps BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS text_primary_color TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS text_muted_color TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS page_background TEXT NOT NULL DEFAULT 'WHITE',
    ADD COLUMN IF NOT EXISTS link_color TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS skills_proficiency TEXT NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS languages_layout TEXT NOT NULL DEFAULT 'LIST',
    ADD COLUMN IF NOT EXISTS certifications_layout TEXT NOT NULL DEFAULT 'LIST',
    ADD COLUMN IF NOT EXISTS keep_sections_together BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS max_items_before_break INT,
    ADD COLUMN IF NOT EXISTS footer_style TEXT NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS export_filename_template TEXT NOT NULL DEFAULT '{name}-resume';

ALTER TABLE resume_sections
    ADD COLUMN IF NOT EXISTS display_title TEXT;
