ALTER TABLE resume_settings
    ADD COLUMN IF NOT EXISTS column_layout TEXT NOT NULL DEFAULT 'SINGLE',
    ADD COLUMN IF NOT EXISTS sidebar_position TEXT NOT NULL DEFAULT 'LEFT',
    ADD COLUMN IF NOT EXISTS sidebar_width TEXT NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN IF NOT EXISTS design_preset_id TEXT NOT NULL DEFAULT 'MODERN',
    ADD COLUMN IF NOT EXISTS photo_position TEXT NOT NULL DEFAULT 'HEADER_LEFT',
    ADD COLUMN IF NOT EXISTS photo_size TEXT NOT NULL DEFAULT 'M',
    ADD COLUMN IF NOT EXISTS contact_layout TEXT NOT NULL DEFAULT 'INLINE',
    ADD COLUMN IF NOT EXISTS contact_fields JSONB NOT NULL DEFAULT '["EMAIL","PHONE","LOCATION","WEBSITE"]'::jsonb;
