ALTER TABLE resume_settings
    ADD COLUMN IF NOT EXISTS date_format TEXT NOT NULL DEFAULT 'MON_YYYY',
    ADD COLUMN IF NOT EXISTS date_position TEXT NOT NULL DEFAULT 'RIGHT',
    ADD COLUMN IF NOT EXISTS skills_layout TEXT NOT NULL DEFAULT 'LIST',
    ADD COLUMN IF NOT EXISTS ats_mode BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE resume_sections
    ADD COLUMN IF NOT EXISTS show_in_preview BOOLEAN NOT NULL DEFAULT TRUE;
