ALTER TABLE resume_settings
    ADD COLUMN IF NOT EXISTS margin_horizontal_mm DOUBLE PRECISION NOT NULL DEFAULT 12,
    ADD COLUMN IF NOT EXISTS margin_vertical_mm DOUBLE PRECISION NOT NULL DEFAULT 12;
