// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddResumeSectionItemInput struct {
	ResumeID  string         `json:"resumeId"`
	SectionID string         `json:"sectionId"`
	Headline  *string        `json:"headline,omitempty"`
	Body      *string        `json:"body,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
}

type AssistantActionLog struct {
	ID        string         `json:"id"`
	MessageID string         `json:"messageId"`
	Op        string         `json:"op"`
	Payload   map[string]any `json:"payload"`
	Success   bool           `json:"success"`
	Error     *string        `json:"error,omitempty"`
	CreatedAt string         `json:"createdAt"`
}

type AssistantAttachmentInput struct {
	Name          string  `json:"name"`
	MimeType      string  `json:"mimeType"`
	ContentBase64 *string `json:"contentBase64,omitempty"`
	ExtractedText *string `json:"extractedText,omitempty"`
}

type AssistantContextInput struct {
	View          AssistantView `json:"view"`
	ResumeID      *string       `json:"resumeId,omitempty"`
	SectionID     *string       `json:"sectionId,omitempty"`
	SectionItemID *string       `json:"sectionItemId,omitempty"`
	JobID         *string       `json:"jobId,omitempty"`
}

type AssistantMessage struct {
	ID        string               `json:"id"`
	ThreadID  string               `json:"threadId"`
	Role      AssistantMessageRole `json:"role"`
	Content   string               `json:"content"`
	Context   map[string]any       `json:"context,omitempty"`
	CreatedAt string               `json:"createdAt"`
}

type AssistantThread struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspaceId"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	Preview     *string `json:"preview,omitempty"`
}

type AssistantTurnResult struct {
	Messages          []*AssistantMessage   `json:"messages"`
	ActionLogs        []*AssistantActionLog `json:"actionLogs"`
	AffectedResumeIds []string              `json:"affectedResumeIds"`
	ResumeWithContent *ResumeWithContent    `json:"resumeWithContent,omitempty"`
}

type ConnectionStatus struct {
	Provider    ConnectionProvider `json:"provider"`
	Connected   bool               `json:"connected"`
	Username    *string            `json:"username,omitempty"`
	AvatarURL   *string            `json:"avatarUrl,omitempty"`
	ConnectedAt *string            `json:"connectedAt,omitempty"`
}

type ContactProfile struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspaceId"`
	FullName    string  `json:"fullName"`
	Headline    *string `json:"headline,omitempty"`
	Email       *string `json:"email,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Location    *string `json:"location,omitempty"`
	Website     *string `json:"website,omitempty"`
	LinkedIn    *string `json:"linkedIn,omitempty"`
	Github      *string `json:"github,omitempty"`
	PhotoURL    *string `json:"photoUrl,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type CreateTwinEntryInput struct {
	Type     TwinEntryType  `json:"type"`
	Title    string         `json:"title"`
	Body     string         `json:"body"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

type CvTheme struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	IsSystem bool           `json:"isSystem"`
	Config   map[string]any `json:"config"`
}

type Mutation struct {
}

type ProfilePhotoUpload struct {
	UploadURL   string `json:"uploadUrl"`
	PhotoURL    string `json:"photoUrl"`
	ContentType string `json:"contentType"`
	MaxBytes    int    `json:"maxBytes"`
}

type Query struct {
}

type Resume struct {
	ID               string  `json:"id"`
	WorkspaceID      string  `json:"workspaceId"`
	Title            string  `json:"title"`
	ContactProfileID *string `json:"contactProfileId,omitempty"`
	CreatedBy        string  `json:"createdBy"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
}

type ResumeSettings struct {
	ResumeID           string     `json:"resumeId"`
	ThemeID            string     `json:"themeId"`
	FontSize           FontSize   `json:"fontSize"`
	PageFormat         PageFormat `json:"pageFormat"`
	MarginHorizontalMm float64    `json:"marginHorizontalMm"`
	MarginVerticalMm   float64    `json:"marginVerticalMm"`
	ShowPhoto          bool       `json:"showPhoto"`
	Locale             string     `json:"locale"`
}

type ResumeWithContent struct {
	Resume         *Resume             `json:"resume"`
	ContactProfile *ContactProfile     `json:"contactProfile,omitempty"`
	Settings       *ResumeSettings     `json:"settings"`
	Theme          *CvTheme            `json:"theme"`
	Sections       []*SectionWithItems `json:"sections"`
}

type Section struct {
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspaceId"`
	Type        SectionType `json:"type"`
	Title       string      `json:"title"`
	Description *string     `json:"description,omitempty"`
	CreatedBy   string      `json:"createdBy"`
	CreatedAt   string      `json:"createdAt"`
	UpdatedAt   string      `json:"updatedAt"`
}

type SectionItem struct {
	ID            string         `json:"id"`
	WorkspaceID   string         `json:"workspaceId"`
	Type          SectionType    `json:"type"`
	Headline      string         `json:"headline"`
	Body          string         `json:"body"`
	Metadata      map[string]any `json:"metadata"`
	ShowInPreview bool           `json:"showInPreview"`
	CreatedBy     string         `json:"createdBy"`
	CreatedAt     string         `json:"createdAt"`
	UpdatedAt     string         `json:"updatedAt"`
}

type SectionItemUsage struct {
	SectionItem *SectionItem `json:"sectionItem"`
	Sections    []*Section   `json:"sections"`
	Resumes     []*Resume    `json:"resumes"`
}

type SectionWithItems struct {
	Section *Section       `json:"section"`
	Items   []*SectionItem `json:"items"`
}

type TrackedJob struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspaceId"`
	URL         string         `json:"url"`
	Title       string         `json:"title"`
	Company     string         `json:"company"`
	Status      JobStatus      `json:"status"`
	Notes       string         `json:"notes"`
	ResumeID    *string        `json:"resumeId,omitempty"`
	CoverLetter string         `json:"coverLetter"`
	Metadata    map[string]any `json:"metadata"`
	CreatedBy   string         `json:"createdBy"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
}

type TwinEntry struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspaceId"`
	Type        TwinEntryType  `json:"type"`
	Title       string         `json:"title"`
	Body        string         `json:"body"`
	Metadata    map[string]any `json:"metadata"`
	SortOrder   int            `json:"sortOrder"`
	CreatedBy   string         `json:"createdBy"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
}

type UpdateContactProfileInput struct {
	ResumeID string  `json:"resumeId"`
	FullName *string `json:"fullName,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Email    *string `json:"email,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Location *string `json:"location,omitempty"`
	Website  *string `json:"website,omitempty"`
	LinkedIn *string `json:"linkedIn,omitempty"`
	Github   *string `json:"github,omitempty"`
	PhotoURL *string `json:"photoUrl,omitempty"`
}

type UpdateResumeSectionItemInput struct {
	ResumeID      string         `json:"resumeId"`
	SectionID     string         `json:"sectionId"`
	SectionItemID string         `json:"sectionItemId"`
	Headline      *string        `json:"headline,omitempty"`
	Body          *string        `json:"body,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

type UpdateResumeSectionItemVisibilityInput struct {
	ResumeID      string `json:"resumeId"`
	SectionID     string `json:"sectionId"`
	SectionItemID string `json:"sectionItemId"`
	ShowInPreview bool   `json:"showInPreview"`
}

type UpdateResumeSettingsInput struct {
	ResumeID           string      `json:"resumeId"`
	PageFormat         *PageFormat `json:"pageFormat,omitempty"`
	FontSize           *FontSize   `json:"fontSize,omitempty"`
	MarginHorizontalMm *float64    `json:"marginHorizontalMm,omitempty"`
	MarginVerticalMm   *float64    `json:"marginVerticalMm,omitempty"`
	ThemeID            *string     `json:"themeId,omitempty"`
	ShowPhoto          *bool       `json:"showPhoto,omitempty"`
	Locale             *string     `json:"locale,omitempty"`
}

type UpdateTrackedJobInput struct {
	ID          string         `json:"id"`
	Title       *string        `json:"title,omitempty"`
	Company     *string        `json:"company,omitempty"`
	Status      *JobStatus     `json:"status,omitempty"`
	Notes       *string        `json:"notes,omitempty"`
	ResumeID    *string        `json:"resumeId,omitempty"`
	CoverLetter *string        `json:"coverLetter,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

type UpdateTwinEntryInput struct {
	ID        string         `json:"id"`
	Type      *TwinEntryType `json:"type,omitempty"`
	Title     *string        `json:"title,omitempty"`
	Body      *string        `json:"body,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
	SortOrder *int           `json:"sortOrder,omitempty"`
}

type User struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	DisplayName string  `json:"displayName"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Workspace struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	OwnerID   string `json:"ownerId"`
	Plan      string `json:"plan"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type WorkspaceStats struct {
	ResumeCount      int `json:"resumeCount"`
	SectionCount     int `json:"sectionCount"`
	SectionItemCount int `json:"sectionItemCount"`
}

type AssistantMessageRole string

const (
	AssistantMessageRoleUser      AssistantMessageRole = "USER"
	AssistantMessageRoleAssistant AssistantMessageRole = "ASSISTANT"
	AssistantMessageRoleSystem    AssistantMessageRole = "SYSTEM"
)

var AllAssistantMessageRole = []AssistantMessageRole{
	AssistantMessageRoleUser,
	AssistantMessageRoleAssistant,
	AssistantMessageRoleSystem,
}

func (e AssistantMessageRole) IsValid() bool {
	switch e {
	case AssistantMessageRoleUser, AssistantMessageRoleAssistant, AssistantMessageRoleSystem:
		return true
	}
	return false
}

func (e AssistantMessageRole) String() string {
	return string(e)
}

func (e *AssistantMessageRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssistantMessageRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssistantMessageRole", str)
	}
	return nil
}

func (e AssistantMessageRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssistantMessageRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssistantMessageRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssistantView string

const (
	AssistantViewResumes      AssistantView = "RESUMES"
	AssistantViewSections     AssistantView = "SECTIONS"
	AssistantViewItems        AssistantView = "ITEMS"
	AssistantViewResumeDetail AssistantView = "RESUME_DETAIL"
	AssistantViewDigitalTwin  AssistantView = "DIGITAL_TWIN"
	AssistantViewJobTracker   AssistantView = "JOB_TRACKER"
)

var AllAssistantView = []AssistantView{
	AssistantViewResumes,
	AssistantViewSections,
	AssistantViewItems,
	AssistantViewResumeDetail,
	AssistantViewDigitalTwin,
	AssistantViewJobTracker,
}

func (e AssistantView) IsValid() bool {
	switch e {
	case AssistantViewResumes, AssistantViewSections, AssistantViewItems, AssistantViewResumeDetail, AssistantViewDigitalTwin, AssistantViewJobTracker:
		return true
	}
	return false
}

func (e AssistantView) String() string {
	return string(e)
}

func (e *AssistantView) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssistantView(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssistantView", str)
	}
	return nil
}

func (e AssistantView) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssistantView) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssistantView) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionProvider string

const (
	ConnectionProviderGithub ConnectionProvider = "GITHUB"
)

var AllConnectionProvider = []ConnectionProvider{
	ConnectionProviderGithub,
}

func (e ConnectionProvider) IsValid() bool {
	switch e {
	case ConnectionProviderGithub:
		return true
	}
	return false
}

func (e ConnectionProvider) String() string {
	return string(e)
}

func (e *ConnectionProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionProvider", str)
	}
	return nil
}

func (e ConnectionProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FontSize string

const (
	FontSizeS FontSize = "S"
	FontSizeM FontSize = "M"
	FontSizeL FontSize = "L"
)

var AllFontSize = []FontSize{
	FontSizeS,
	FontSizeM,
	FontSizeL,
}

func (e FontSize) IsValid() bool {
	switch e {
	case FontSizeS, FontSizeM, FontSizeL:
		return true
	}
	return false
}

func (e FontSize) String() string {
	return string(e)
}

func (e *FontSize) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FontSize(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FontSize", str)
	}
	return nil
}

func (e FontSize) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FontSize) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FontSize) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobStatus string

const (
	JobStatusSaved     JobStatus = "SAVED"
	JobStatusApplied   JobStatus = "APPLIED"
	JobStatusInterview JobStatus = "INTERVIEW"
	JobStatusOffer     JobStatus = "OFFER"
	JobStatusRejected  JobStatus = "REJECTED"
)

var AllJobStatus = []JobStatus{
	JobStatusSaved,
	JobStatusApplied,
	JobStatusInterview,
	JobStatusOffer,
	JobStatusRejected,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusSaved, JobStatusApplied, JobStatusInterview, JobStatusOffer, JobStatusRejected:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Spoken language proficiency — stored in section item metadata.level (LANGUAGES).
type LanguageLevel string

const (
	LanguageLevelBeginner     LanguageLevel = "BEGINNER"
	LanguageLevelIntermediate LanguageLevel = "INTERMEDIATE"
	LanguageLevelProficient   LanguageLevel = "PROFICIENT"
	LanguageLevelFluent       LanguageLevel = "FLUENT"
	LanguageLevelNative       LanguageLevel = "NATIVE"
)

var AllLanguageLevel = []LanguageLevel{
	LanguageLevelBeginner,
	LanguageLevelIntermediate,
	LanguageLevelProficient,
	LanguageLevelFluent,
	LanguageLevelNative,
}

func (e LanguageLevel) IsValid() bool {
	switch e {
	case LanguageLevelBeginner, LanguageLevelIntermediate, LanguageLevelProficient, LanguageLevelFluent, LanguageLevelNative:
		return true
	}
	return false
}

func (e LanguageLevel) String() string {
	return string(e)
}

func (e *LanguageLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LanguageLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LanguageLevel", str)
	}
	return nil
}

func (e LanguageLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LanguageLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LanguageLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PageFormat string

const (
	PageFormatA4     PageFormat = "A4"
	PageFormatLetter PageFormat = "LETTER"
)

var AllPageFormat = []PageFormat{
	PageFormatA4,
	PageFormatLetter,
}

func (e PageFormat) IsValid() bool {
	switch e {
	case PageFormatA4, PageFormatLetter:
		return true
	}
	return false
}

func (e PageFormat) String() string {
	return string(e)
}

func (e *PageFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PageFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PageFormat", str)
	}
	return nil
}

func (e PageFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PageFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PageFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SectionType string

const (
	SectionTypeSummary        SectionType = "SUMMARY"
	SectionTypeExperience     SectionType = "EXPERIENCE"
	SectionTypeEducation      SectionType = "EDUCATION"
	SectionTypeSkills         SectionType = "SKILLS"
	SectionTypeProjects       SectionType = "PROJECTS"
	SectionTypeCertifications SectionType = "CERTIFICATIONS"
	SectionTypeLanguages      SectionType = "LANGUAGES"
	SectionTypeOrganizations  SectionType = "ORGANIZATIONS"
	SectionTypePublications   SectionType = "PUBLICATIONS"
	SectionTypeAwards         SectionType = "AWARDS"
	SectionTypeVolunteer      SectionType = "VOLUNTEER"
	SectionTypeCustom         SectionType = "CUSTOM"
)

var AllSectionType = []SectionType{
	SectionTypeSummary,
	SectionTypeExperience,
	SectionTypeEducation,
	SectionTypeSkills,
	SectionTypeProjects,
	SectionTypeCertifications,
	SectionTypeLanguages,
	SectionTypeOrganizations,
	SectionTypePublications,
	SectionTypeAwards,
	SectionTypeVolunteer,
	SectionTypeCustom,
}

func (e SectionType) IsValid() bool {
	switch e {
	case SectionTypeSummary, SectionTypeExperience, SectionTypeEducation, SectionTypeSkills, SectionTypeProjects, SectionTypeCertifications, SectionTypeLanguages, SectionTypeOrganizations, SectionTypePublications, SectionTypeAwards, SectionTypeVolunteer, SectionTypeCustom:
		return true
	}
	return false
}

func (e SectionType) String() string {
	return string(e)
}

func (e *SectionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SectionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SectionType", str)
	}
	return nil
}

func (e SectionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SectionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SectionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Technical/professional skill proficiency — stored in section item metadata.level (SKILLS) and Twin SKILL_AREA.
type SkillLevel string

const (
	SkillLevelBeginner     SkillLevel = "BEGINNER"
	SkillLevelIntermediate SkillLevel = "INTERMEDIATE"
	SkillLevelProficient   SkillLevel = "PROFICIENT"
	SkillLevelAdvanced     SkillLevel = "ADVANCED"
	SkillLevelExpert       SkillLevel = "EXPERT"
)

var AllSkillLevel = []SkillLevel{
	SkillLevelBeginner,
	SkillLevelIntermediate,
	SkillLevelProficient,
	SkillLevelAdvanced,
	SkillLevelExpert,
}

func (e SkillLevel) IsValid() bool {
	switch e {
	case SkillLevelBeginner, SkillLevelIntermediate, SkillLevelProficient, SkillLevelAdvanced, SkillLevelExpert:
		return true
	}
	return false
}

func (e SkillLevel) String() string {
	return string(e)
}

func (e *SkillLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SkillLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SkillLevel", str)
	}
	return nil
}

func (e SkillLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SkillLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SkillLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TwinEntryType string

const (
	TwinEntryTypeExperience TwinEntryType = "EXPERIENCE"
	TwinEntryTypeEducation  TwinEntryType = "EDUCATION"
	TwinEntryTypeProject    TwinEntryType = "PROJECT"
	TwinEntryTypeSkillArea  TwinEntryType = "SKILL_AREA"
	TwinEntryTypeOther      TwinEntryType = "OTHER"
)

var AllTwinEntryType = []TwinEntryType{
	TwinEntryTypeExperience,
	TwinEntryTypeEducation,
	TwinEntryTypeProject,
	TwinEntryTypeSkillArea,
	TwinEntryTypeOther,
}

func (e TwinEntryType) IsValid() bool {
	switch e {
	case TwinEntryTypeExperience, TwinEntryTypeEducation, TwinEntryTypeProject, TwinEntryTypeSkillArea, TwinEntryTypeOther:
		return true
	}
	return false
}

func (e TwinEntryType) String() string {
	return string(e)
}

func (e *TwinEntryType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TwinEntryType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TwinEntryType", str)
	}
	return nil
}

func (e TwinEntryType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TwinEntryType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TwinEntryType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
