// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddPortfolioProjectInput struct {
	PortfolioID string   `json:"portfolioId"`
	Title       string   `json:"title"`
	Tagline     *string  `json:"tagline,omitempty"`
	Problem     *string  `json:"problem,omitempty"`
	Approach    *string  `json:"approach,omitempty"`
	Outcome     *string  `json:"outcome,omitempty"`
	TechStack   []string `json:"techStack,omitempty"`
	LiveURL     *string  `json:"liveUrl,omitempty"`
	RepoURL     *string  `json:"repoUrl,omitempty"`
	ImageURL    *string  `json:"imageUrl,omitempty"`
	Featured    *bool    `json:"featured,omitempty"`
}

type AddPortfolioSkillInput struct {
	PortfolioID string  `json:"portfolioId"`
	Name        string  `json:"name"`
	Category    *string `json:"category,omitempty"`
}

type AddPortfolioTestimonialInput struct {
	PortfolioID string  `json:"portfolioId"`
	Quote       string  `json:"quote"`
	Author      *string `json:"author,omitempty"`
	Role        *string `json:"role,omitempty"`
}

type AddResumeSectionItemInput struct {
	ResumeID  string         `json:"resumeId"`
	SectionID string         `json:"sectionId"`
	Headline  *string        `json:"headline,omitempty"`
	Body      *string        `json:"body,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
}

type AssistantActionLog struct {
	ID        string         `json:"id"`
	MessageID string         `json:"messageId"`
	Op        string         `json:"op"`
	Payload   map[string]any `json:"payload"`
	Success   bool           `json:"success"`
	Error     *string        `json:"error,omitempty"`
	CreatedAt string         `json:"createdAt"`
}

type AssistantAttachmentInput struct {
	Name          string  `json:"name"`
	MimeType      string  `json:"mimeType"`
	ContentBase64 *string `json:"contentBase64,omitempty"`
	ExtractedText *string `json:"extractedText,omitempty"`
}

// Result of the cheap pre-classification layer, exposed for the admin experiment page.
type AssistantClassification struct {
	Category   AssistantCategory `json:"category"`
	Confidence float64           `json:"confidence"`
	Tags       []string          `json:"tags"`
	Reason     string            `json:"reason"`
	// Where the decision came from: fast-path, classifier, or fallback.
	Source string `json:"source"`
	// True when the request is handled before the main agent (out of scope, unclear, greeting).
	ScopeHandled bool `json:"scopeHandled"`
	// The canned reply used when scopeHandled is true (out of scope / unclear / greeting).
	CannedReply *string `json:"cannedReply,omitempty"`
	// Dictionary entries selected for this category/tags.
	SelectedEntries []*KnowledgeEntry `json:"selectedEntries"`
	// The guidance block that would be injected into the main agent prompt.
	Guidance string `json:"guidance"`
}

type AssistantContextInput struct {
	View          AssistantView `json:"view"`
	ResumeID      *string       `json:"resumeId,omitempty"`
	PortfolioID   *string       `json:"portfolioId,omitempty"`
	SectionID     *string       `json:"sectionId,omitempty"`
	SectionItemID *string       `json:"sectionItemId,omitempty"`
	JobID         *string       `json:"jobId,omitempty"`
}

type AssistantMessage struct {
	ID        string               `json:"id"`
	ThreadID  string               `json:"threadId"`
	Role      AssistantMessageRole `json:"role"`
	Content   string               `json:"content"`
	Context   map[string]any       `json:"context,omitempty"`
	CreatedAt string               `json:"createdAt"`
}

type AssistantThread struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspaceId"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	Preview     *string `json:"preview,omitempty"`
}

type AssistantTurnResult struct {
	Messages             []*AssistantMessage   `json:"messages"`
	ActionLogs           []*AssistantActionLog `json:"actionLogs"`
	AffectedResumeIds    []string              `json:"affectedResumeIds"`
	AffectedPortfolioIds []string              `json:"affectedPortfolioIds"`
	ResumeWithContent    *ResumeWithContent    `json:"resumeWithContent,omitempty"`
	PortfolioWithContent *PortfolioWithContent `json:"portfolioWithContent,omitempty"`
}

type ConnectionStatus struct {
	Provider    ConnectionProvider `json:"provider"`
	Connected   bool               `json:"connected"`
	Username    *string            `json:"username,omitempty"`
	AvatarURL   *string            `json:"avatarUrl,omitempty"`
	ConnectedAt *string            `json:"connectedAt,omitempty"`
}

type ContactProfile struct {
	ID                string  `json:"id"`
	WorkspaceID       string  `json:"workspaceId"`
	FullName          string  `json:"fullName"`
	Headline          *string `json:"headline,omitempty"`
	Email             *string `json:"email,omitempty"`
	Phone             *string `json:"phone,omitempty"`
	Location          *string `json:"location,omitempty"`
	Website           *string `json:"website,omitempty"`
	LinkedIn          *string `json:"linkedIn,omitempty"`
	Github            *string `json:"github,omitempty"`
	PhotoURL          *string `json:"photoUrl,omitempty"`
	LinkedinPhotoURL  *string `json:"linkedinPhotoUrl,omitempty"`
	GithubPhotoURL    *string `json:"githubPhotoUrl,omitempty"`
	EffectivePhotoURL *string `json:"effectivePhotoUrl,omitempty"`
	CreatedAt         string  `json:"createdAt"`
	UpdatedAt         string  `json:"updatedAt"`
}

type CreateKnowledgeEntryInput struct {
	Slug     string            `json:"slug"`
	Title    string            `json:"title"`
	Category AssistantCategory `json:"category"`
	Tags     []string          `json:"tags,omitempty"`
	Body     string            `json:"body"`
	Enabled  *bool             `json:"enabled,omitempty"`
}

type CreateTwinEntryInput struct {
	Type     TwinEntryType  `json:"type"`
	Title    string         `json:"title"`
	Body     string         `json:"body"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

type CvTheme struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	IsSystem bool           `json:"isSystem"`
	Config   map[string]any `json:"config"`
}

// A curated, tag-keyed guidance entry the agent injects into context based on the detected category.
type KnowledgeEntry struct {
	ID        string            `json:"id"`
	Slug      string            `json:"slug"`
	Title     string            `json:"title"`
	Category  AssistantCategory `json:"category"`
	Tags      []string          `json:"tags"`
	Body      string            `json:"body"`
	Enabled   bool              `json:"enabled"`
	CreatedAt string            `json:"createdAt"`
	UpdatedAt string            `json:"updatedAt"`
}

type Mutation struct {
}

type Portfolio struct {
	ID               string  `json:"id"`
	WorkspaceID      string  `json:"workspaceId"`
	Title            string  `json:"title"`
	Tagline          string  `json:"tagline"`
	About            string  `json:"about"`
	ContactProfileID *string `json:"contactProfileId,omitempty"`
	CreatedBy        string  `json:"createdBy"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
}

type PortfolioProject struct {
	ID            string   `json:"id"`
	PortfolioID   string   `json:"portfolioId"`
	Title         string   `json:"title"`
	Tagline       string   `json:"tagline"`
	Problem       string   `json:"problem"`
	Approach      string   `json:"approach"`
	Outcome       string   `json:"outcome"`
	TechStack     []string `json:"techStack"`
	LiveURL       *string  `json:"liveUrl,omitempty"`
	RepoURL       *string  `json:"repoUrl,omitempty"`
	ImageURL      *string  `json:"imageUrl,omitempty"`
	Featured      bool     `json:"featured"`
	ShowInPreview bool     `json:"showInPreview"`
	SortOrder     int      `json:"sortOrder"`
	CreatedAt     string   `json:"createdAt"`
	UpdatedAt     string   `json:"updatedAt"`
}

type PortfolioSettings struct {
	PortfolioID string          `json:"portfolioId"`
	ThemeID     string          `json:"themeId"`
	Layout      PortfolioLayout `json:"layout"`
	AccentColor string          `json:"accentColor"`
	ShowPhoto   bool            `json:"showPhoto"`
	Locale      string          `json:"locale"`
}

type PortfolioSkill struct {
	ID            string  `json:"id"`
	PortfolioID   string  `json:"portfolioId"`
	Name          string  `json:"name"`
	Category      *string `json:"category,omitempty"`
	ShowInPreview bool    `json:"showInPreview"`
	SortOrder     int     `json:"sortOrder"`
}

type PortfolioTestimonial struct {
	ID            string `json:"id"`
	PortfolioID   string `json:"portfolioId"`
	Quote         string `json:"quote"`
	Author        string `json:"author"`
	Role          string `json:"role"`
	ShowInPreview bool   `json:"showInPreview"`
	SortOrder     int    `json:"sortOrder"`
}

type PortfolioWithContent struct {
	Portfolio      *Portfolio              `json:"portfolio"`
	ContactProfile *ContactProfile         `json:"contactProfile,omitempty"`
	Settings       *PortfolioSettings      `json:"settings"`
	Theme          *CvTheme                `json:"theme"`
	Projects       []*PortfolioProject     `json:"projects"`
	Skills         []*PortfolioSkill       `json:"skills"`
	Testimonials   []*PortfolioTestimonial `json:"testimonials"`
}

type ProfilePhotoUpload struct {
	UploadURL   string `json:"uploadUrl"`
	PhotoURL    string `json:"photoUrl"`
	ContentType string `json:"contentType"`
	MaxBytes    int    `json:"maxBytes"`
}

type Query struct {
}

type Resume struct {
	ID               string  `json:"id"`
	WorkspaceID      string  `json:"workspaceId"`
	Title            string  `json:"title"`
	ContactProfileID *string `json:"contactProfileId,omitempty"`
	CreatedBy        string  `json:"createdBy"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
}

type ResumeSettings struct {
	ResumeID                string          `json:"resumeId"`
	ThemeID                 string          `json:"themeId"`
	FontSize                FontSize        `json:"fontSize"`
	ContactNameFontSize     FontSize        `json:"contactNameFontSize"`
	ContactHeadlineFontSize FontSize        `json:"contactHeadlineFontSize"`
	ContactDetailsFontSize  FontSize        `json:"contactDetailsFontSize"`
	SectionTitleFontSize    FontSize        `json:"sectionTitleFontSize"`
	ItemTitleFontSize       FontSize        `json:"itemTitleFontSize"`
	ItemMetaFontSize        FontSize        `json:"itemMetaFontSize"`
	PageFormat              PageFormat      `json:"pageFormat"`
	MarginHorizontalMm      float64         `json:"marginHorizontalMm"`
	MarginVerticalMm        float64         `json:"marginVerticalMm"`
	ShowPhoto               bool            `json:"showPhoto"`
	ItemTitleLayout         ItemTitleLayout `json:"itemTitleLayout"`
	Locale                  string          `json:"locale"`
}

type ResumeWithContent struct {
	Resume         *Resume             `json:"resume"`
	ContactProfile *ContactProfile     `json:"contactProfile,omitempty"`
	Settings       *ResumeSettings     `json:"settings"`
	Theme          *CvTheme            `json:"theme"`
	Sections       []*SectionWithItems `json:"sections"`
}

type Section struct {
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspaceId"`
	Type        SectionType `json:"type"`
	Title       string      `json:"title"`
	Description *string     `json:"description,omitempty"`
	CreatedBy   string      `json:"createdBy"`
	CreatedAt   string      `json:"createdAt"`
	UpdatedAt   string      `json:"updatedAt"`
}

type SectionItem struct {
	ID            string         `json:"id"`
	WorkspaceID   string         `json:"workspaceId"`
	Type          SectionType    `json:"type"`
	Headline      string         `json:"headline"`
	Body          string         `json:"body"`
	Metadata      map[string]any `json:"metadata"`
	ShowInPreview bool           `json:"showInPreview"`
	CreatedBy     string         `json:"createdBy"`
	CreatedAt     string         `json:"createdAt"`
	UpdatedAt     string         `json:"updatedAt"`
}

type SectionItemUsage struct {
	SectionItem *SectionItem `json:"sectionItem"`
	Sections    []*Section   `json:"sections"`
	Resumes     []*Resume    `json:"resumes"`
	Portfolios  []*Portfolio `json:"portfolios"`
}

type SectionWithItems struct {
	Section *Section       `json:"section"`
	Items   []*SectionItem `json:"items"`
}

type SetPortfolioProjectVisibilityInput struct {
	PortfolioID   string `json:"portfolioId"`
	ProjectID     string `json:"projectId"`
	ShowInPreview bool   `json:"showInPreview"`
}

type TrackedJob struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspaceId"`
	URL         string         `json:"url"`
	Title       string         `json:"title"`
	Company     string         `json:"company"`
	Status      JobStatus      `json:"status"`
	Notes       string         `json:"notes"`
	ResumeID    *string        `json:"resumeId,omitempty"`
	CoverLetter string         `json:"coverLetter"`
	Metadata    map[string]any `json:"metadata"`
	CreatedBy   string         `json:"createdBy"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
}

type TwinEntry struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspaceId"`
	Type        TwinEntryType  `json:"type"`
	Title       string         `json:"title"`
	Body        string         `json:"body"`
	Metadata    map[string]any `json:"metadata"`
	SortOrder   int            `json:"sortOrder"`
	CreatedBy   string         `json:"createdBy"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
}

type UpdateContactProfileInput struct {
	ResumeID         string  `json:"resumeId"`
	FullName         *string `json:"fullName,omitempty"`
	Headline         *string `json:"headline,omitempty"`
	Email            *string `json:"email,omitempty"`
	Phone            *string `json:"phone,omitempty"`
	Location         *string `json:"location,omitempty"`
	Website          *string `json:"website,omitempty"`
	LinkedIn         *string `json:"linkedIn,omitempty"`
	Github           *string `json:"github,omitempty"`
	PhotoURL         *string `json:"photoUrl,omitempty"`
	LinkedinPhotoURL *string `json:"linkedinPhotoUrl,omitempty"`
	GithubPhotoURL   *string `json:"githubPhotoUrl,omitempty"`
}

type UpdateKnowledgeEntryInput struct {
	ID       string             `json:"id"`
	Slug     *string            `json:"slug,omitempty"`
	Title    *string            `json:"title,omitempty"`
	Category *AssistantCategory `json:"category,omitempty"`
	Tags     []string           `json:"tags,omitempty"`
	Body     *string            `json:"body,omitempty"`
	Enabled  *bool              `json:"enabled,omitempty"`
}

type UpdatePortfolioContactProfileInput struct {
	PortfolioID      string  `json:"portfolioId"`
	FullName         *string `json:"fullName,omitempty"`
	Headline         *string `json:"headline,omitempty"`
	Email            *string `json:"email,omitempty"`
	Phone            *string `json:"phone,omitempty"`
	Location         *string `json:"location,omitempty"`
	Website          *string `json:"website,omitempty"`
	LinkedIn         *string `json:"linkedIn,omitempty"`
	Github           *string `json:"github,omitempty"`
	PhotoURL         *string `json:"photoUrl,omitempty"`
	LinkedinPhotoURL *string `json:"linkedinPhotoUrl,omitempty"`
	GithubPhotoURL   *string `json:"githubPhotoUrl,omitempty"`
}

type UpdatePortfolioProjectInput struct {
	PortfolioID   string   `json:"portfolioId"`
	ProjectID     string   `json:"projectId"`
	Title         *string  `json:"title,omitempty"`
	Tagline       *string  `json:"tagline,omitempty"`
	Problem       *string  `json:"problem,omitempty"`
	Approach      *string  `json:"approach,omitempty"`
	Outcome       *string  `json:"outcome,omitempty"`
	TechStack     []string `json:"techStack,omitempty"`
	LiveURL       *string  `json:"liveUrl,omitempty"`
	RepoURL       *string  `json:"repoUrl,omitempty"`
	ImageURL      *string  `json:"imageUrl,omitempty"`
	Featured      *bool    `json:"featured,omitempty"`
	ShowInPreview *bool    `json:"showInPreview,omitempty"`
}

type UpdatePortfolioSettingsInput struct {
	PortfolioID string           `json:"portfolioId"`
	Layout      *PortfolioLayout `json:"layout,omitempty"`
	AccentColor *string          `json:"accentColor,omitempty"`
	ThemeID     *string          `json:"themeId,omitempty"`
	ShowPhoto   *bool            `json:"showPhoto,omitempty"`
	Locale      *string          `json:"locale,omitempty"`
}

type UpdatePortfolioSkillInput struct {
	PortfolioID   string  `json:"portfolioId"`
	SkillID       string  `json:"skillId"`
	Name          *string `json:"name,omitempty"`
	Category      *string `json:"category,omitempty"`
	ShowInPreview *bool   `json:"showInPreview,omitempty"`
}

type UpdatePortfolioTestimonialInput struct {
	PortfolioID   string  `json:"portfolioId"`
	TestimonialID string  `json:"testimonialId"`
	Quote         *string `json:"quote,omitempty"`
	Author        *string `json:"author,omitempty"`
	Role          *string `json:"role,omitempty"`
	ShowInPreview *bool   `json:"showInPreview,omitempty"`
}

type UpdateResumeSectionItemInput struct {
	ResumeID      string         `json:"resumeId"`
	SectionID     string         `json:"sectionId"`
	SectionItemID string         `json:"sectionItemId"`
	Headline      *string        `json:"headline,omitempty"`
	Body          *string        `json:"body,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

type UpdateResumeSectionItemVisibilityInput struct {
	ResumeID      string `json:"resumeId"`
	SectionID     string `json:"sectionId"`
	SectionItemID string `json:"sectionItemId"`
	ShowInPreview bool   `json:"showInPreview"`
}

type UpdateResumeSettingsInput struct {
	ResumeID                string           `json:"resumeId"`
	PageFormat              *PageFormat      `json:"pageFormat,omitempty"`
	FontSize                *FontSize        `json:"fontSize,omitempty"`
	ContactNameFontSize     *FontSize        `json:"contactNameFontSize,omitempty"`
	ContactHeadlineFontSize *FontSize        `json:"contactHeadlineFontSize,omitempty"`
	ContactDetailsFontSize  *FontSize        `json:"contactDetailsFontSize,omitempty"`
	SectionTitleFontSize    *FontSize        `json:"sectionTitleFontSize,omitempty"`
	ItemTitleFontSize       *FontSize        `json:"itemTitleFontSize,omitempty"`
	ItemMetaFontSize        *FontSize        `json:"itemMetaFontSize,omitempty"`
	MarginHorizontalMm      *float64         `json:"marginHorizontalMm,omitempty"`
	MarginVerticalMm        *float64         `json:"marginVerticalMm,omitempty"`
	ThemeID                 *string          `json:"themeId,omitempty"`
	ShowPhoto               *bool            `json:"showPhoto,omitempty"`
	ItemTitleLayout         *ItemTitleLayout `json:"itemTitleLayout,omitempty"`
	Locale                  *string          `json:"locale,omitempty"`
}

type UpdateTrackedJobInput struct {
	ID          string         `json:"id"`
	Title       *string        `json:"title,omitempty"`
	Company     *string        `json:"company,omitempty"`
	Status      *JobStatus     `json:"status,omitempty"`
	Notes       *string        `json:"notes,omitempty"`
	ResumeID    *string        `json:"resumeId,omitempty"`
	CoverLetter *string        `json:"coverLetter,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

type UpdateTwinEntryInput struct {
	ID        string         `json:"id"`
	Type      *TwinEntryType `json:"type,omitempty"`
	Title     *string        `json:"title,omitempty"`
	Body      *string        `json:"body,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
	SortOrder *int           `json:"sortOrder,omitempty"`
}

type User struct {
	ID          string   `json:"id"`
	Email       string   `json:"email"`
	DisplayName string   `json:"displayName"`
	AvatarURL   *string  `json:"avatarUrl,omitempty"`
	Role        UserRole `json:"role"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}

type Workspace struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	OwnerID   string `json:"ownerId"`
	Plan      string `json:"plan"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type WorkspaceStats struct {
	ResumeCount      int `json:"resumeCount"`
	PortfolioCount   int `json:"portfolioCount"`
	SectionCount     int `json:"sectionCount"`
	SectionItemCount int `json:"sectionItemCount"`
}

// Detected request category from the cheap intent layer that runs before the main agent.
type AssistantCategory string

const (
	AssistantCategoryUpdateCv       AssistantCategory = "UPDATE_CV"
	AssistantCategoryCreateCv       AssistantCategory = "CREATE_CV"
	AssistantCategoryPortfolio      AssistantCategory = "PORTFOLIO"
	AssistantCategoryJobApplication AssistantCategory = "JOB_APPLICATION"
	AssistantCategoryAdvice         AssistantCategory = "ADVICE"
	AssistantCategoryOutOfScope     AssistantCategory = "OUT_OF_SCOPE"
	AssistantCategoryChitchat       AssistantCategory = "CHITCHAT"
	AssistantCategoryUnclear        AssistantCategory = "UNCLEAR"
)

var AllAssistantCategory = []AssistantCategory{
	AssistantCategoryUpdateCv,
	AssistantCategoryCreateCv,
	AssistantCategoryPortfolio,
	AssistantCategoryJobApplication,
	AssistantCategoryAdvice,
	AssistantCategoryOutOfScope,
	AssistantCategoryChitchat,
	AssistantCategoryUnclear,
}

func (e AssistantCategory) IsValid() bool {
	switch e {
	case AssistantCategoryUpdateCv, AssistantCategoryCreateCv, AssistantCategoryPortfolio, AssistantCategoryJobApplication, AssistantCategoryAdvice, AssistantCategoryOutOfScope, AssistantCategoryChitchat, AssistantCategoryUnclear:
		return true
	}
	return false
}

func (e AssistantCategory) String() string {
	return string(e)
}

func (e *AssistantCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssistantCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssistantCategory", str)
	}
	return nil
}

func (e AssistantCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssistantCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssistantCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssistantMessageRole string

const (
	AssistantMessageRoleUser      AssistantMessageRole = "USER"
	AssistantMessageRoleAssistant AssistantMessageRole = "ASSISTANT"
	AssistantMessageRoleSystem    AssistantMessageRole = "SYSTEM"
)

var AllAssistantMessageRole = []AssistantMessageRole{
	AssistantMessageRoleUser,
	AssistantMessageRoleAssistant,
	AssistantMessageRoleSystem,
}

func (e AssistantMessageRole) IsValid() bool {
	switch e {
	case AssistantMessageRoleUser, AssistantMessageRoleAssistant, AssistantMessageRoleSystem:
		return true
	}
	return false
}

func (e AssistantMessageRole) String() string {
	return string(e)
}

func (e *AssistantMessageRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssistantMessageRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssistantMessageRole", str)
	}
	return nil
}

func (e AssistantMessageRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssistantMessageRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssistantMessageRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssistantView string

const (
	AssistantViewResumes         AssistantView = "RESUMES"
	AssistantViewSections        AssistantView = "SECTIONS"
	AssistantViewItems           AssistantView = "ITEMS"
	AssistantViewResumeDetail    AssistantView = "RESUME_DETAIL"
	AssistantViewPortfolios      AssistantView = "PORTFOLIOS"
	AssistantViewPortfolioDetail AssistantView = "PORTFOLIO_DETAIL"
	AssistantViewDigitalTwin     AssistantView = "DIGITAL_TWIN"
	AssistantViewJobTracker      AssistantView = "JOB_TRACKER"
)

var AllAssistantView = []AssistantView{
	AssistantViewResumes,
	AssistantViewSections,
	AssistantViewItems,
	AssistantViewResumeDetail,
	AssistantViewPortfolios,
	AssistantViewPortfolioDetail,
	AssistantViewDigitalTwin,
	AssistantViewJobTracker,
}

func (e AssistantView) IsValid() bool {
	switch e {
	case AssistantViewResumes, AssistantViewSections, AssistantViewItems, AssistantViewResumeDetail, AssistantViewPortfolios, AssistantViewPortfolioDetail, AssistantViewDigitalTwin, AssistantViewJobTracker:
		return true
	}
	return false
}

func (e AssistantView) String() string {
	return string(e)
}

func (e *AssistantView) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssistantView(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssistantView", str)
	}
	return nil
}

func (e AssistantView) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssistantView) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssistantView) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionProvider string

const (
	ConnectionProviderGithub ConnectionProvider = "GITHUB"
)

var AllConnectionProvider = []ConnectionProvider{
	ConnectionProviderGithub,
}

func (e ConnectionProvider) IsValid() bool {
	switch e {
	case ConnectionProviderGithub:
		return true
	}
	return false
}

func (e ConnectionProvider) String() string {
	return string(e)
}

func (e *ConnectionProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionProvider", str)
	}
	return nil
}

func (e ConnectionProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FontSize string

const (
	FontSizeXs FontSize = "XS"
	FontSizeS  FontSize = "S"
	FontSizeM  FontSize = "M"
	FontSizeL  FontSize = "L"
	FontSizeXl FontSize = "XL"
)

var AllFontSize = []FontSize{
	FontSizeXs,
	FontSizeS,
	FontSizeM,
	FontSizeL,
	FontSizeXl,
}

func (e FontSize) IsValid() bool {
	switch e {
	case FontSizeXs, FontSizeS, FontSizeM, FontSizeL, FontSizeXl:
		return true
	}
	return false
}

func (e FontSize) String() string {
	return string(e)
}

func (e *FontSize) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FontSize(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FontSize", str)
	}
	return nil
}

func (e FontSize) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FontSize) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FontSize) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// How section item title and subtitle (role/company, degree/school, etc.) are laid out.
type ItemTitleLayout string

const (
	ItemTitleLayoutStacked ItemTitleLayout = "STACKED"
	ItemTitleLayoutInline  ItemTitleLayout = "INLINE"
)

var AllItemTitleLayout = []ItemTitleLayout{
	ItemTitleLayoutStacked,
	ItemTitleLayoutInline,
}

func (e ItemTitleLayout) IsValid() bool {
	switch e {
	case ItemTitleLayoutStacked, ItemTitleLayoutInline:
		return true
	}
	return false
}

func (e ItemTitleLayout) String() string {
	return string(e)
}

func (e *ItemTitleLayout) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemTitleLayout(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemTitleLayout", str)
	}
	return nil
}

func (e ItemTitleLayout) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ItemTitleLayout) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ItemTitleLayout) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobStatus string

const (
	JobStatusSaved     JobStatus = "SAVED"
	JobStatusApplied   JobStatus = "APPLIED"
	JobStatusInterview JobStatus = "INTERVIEW"
	JobStatusOffer     JobStatus = "OFFER"
	JobStatusRejected  JobStatus = "REJECTED"
)

var AllJobStatus = []JobStatus{
	JobStatusSaved,
	JobStatusApplied,
	JobStatusInterview,
	JobStatusOffer,
	JobStatusRejected,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusSaved, JobStatusApplied, JobStatusInterview, JobStatusOffer, JobStatusRejected:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Spoken language proficiency — stored in section item metadata.level (LANGUAGES).
type LanguageLevel string

const (
	LanguageLevelBeginner     LanguageLevel = "BEGINNER"
	LanguageLevelIntermediate LanguageLevel = "INTERMEDIATE"
	LanguageLevelProficient   LanguageLevel = "PROFICIENT"
	LanguageLevelFluent       LanguageLevel = "FLUENT"
	LanguageLevelNative       LanguageLevel = "NATIVE"
)

var AllLanguageLevel = []LanguageLevel{
	LanguageLevelBeginner,
	LanguageLevelIntermediate,
	LanguageLevelProficient,
	LanguageLevelFluent,
	LanguageLevelNative,
}

func (e LanguageLevel) IsValid() bool {
	switch e {
	case LanguageLevelBeginner, LanguageLevelIntermediate, LanguageLevelProficient, LanguageLevelFluent, LanguageLevelNative:
		return true
	}
	return false
}

func (e LanguageLevel) String() string {
	return string(e)
}

func (e *LanguageLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LanguageLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LanguageLevel", str)
	}
	return nil
}

func (e LanguageLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LanguageLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LanguageLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PageFormat string

const (
	PageFormatA4     PageFormat = "A4"
	PageFormatLetter PageFormat = "LETTER"
)

var AllPageFormat = []PageFormat{
	PageFormatA4,
	PageFormatLetter,
}

func (e PageFormat) IsValid() bool {
	switch e {
	case PageFormatA4, PageFormatLetter:
		return true
	}
	return false
}

func (e PageFormat) String() string {
	return string(e)
}

func (e *PageFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PageFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PageFormat", str)
	}
	return nil
}

func (e PageFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PageFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PageFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PortfolioLayout string

const (
	PortfolioLayoutSingle PortfolioLayout = "SINGLE"
	PortfolioLayoutSplit  PortfolioLayout = "SPLIT"
)

var AllPortfolioLayout = []PortfolioLayout{
	PortfolioLayoutSingle,
	PortfolioLayoutSplit,
}

func (e PortfolioLayout) IsValid() bool {
	switch e {
	case PortfolioLayoutSingle, PortfolioLayoutSplit:
		return true
	}
	return false
}

func (e PortfolioLayout) String() string {
	return string(e)
}

func (e *PortfolioLayout) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PortfolioLayout(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PortfolioLayout", str)
	}
	return nil
}

func (e PortfolioLayout) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PortfolioLayout) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PortfolioLayout) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SectionType string

const (
	SectionTypeSummary        SectionType = "SUMMARY"
	SectionTypeExperience     SectionType = "EXPERIENCE"
	SectionTypeEducation      SectionType = "EDUCATION"
	SectionTypeSkills         SectionType = "SKILLS"
	SectionTypeProjects       SectionType = "PROJECTS"
	SectionTypeCertifications SectionType = "CERTIFICATIONS"
	SectionTypeLanguages      SectionType = "LANGUAGES"
	SectionTypeOrganizations  SectionType = "ORGANIZATIONS"
	SectionTypePublications   SectionType = "PUBLICATIONS"
	SectionTypeAwards         SectionType = "AWARDS"
	SectionTypeVolunteer      SectionType = "VOLUNTEER"
	SectionTypeCustom         SectionType = "CUSTOM"
)

var AllSectionType = []SectionType{
	SectionTypeSummary,
	SectionTypeExperience,
	SectionTypeEducation,
	SectionTypeSkills,
	SectionTypeProjects,
	SectionTypeCertifications,
	SectionTypeLanguages,
	SectionTypeOrganizations,
	SectionTypePublications,
	SectionTypeAwards,
	SectionTypeVolunteer,
	SectionTypeCustom,
}

func (e SectionType) IsValid() bool {
	switch e {
	case SectionTypeSummary, SectionTypeExperience, SectionTypeEducation, SectionTypeSkills, SectionTypeProjects, SectionTypeCertifications, SectionTypeLanguages, SectionTypeOrganizations, SectionTypePublications, SectionTypeAwards, SectionTypeVolunteer, SectionTypeCustom:
		return true
	}
	return false
}

func (e SectionType) String() string {
	return string(e)
}

func (e *SectionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SectionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SectionType", str)
	}
	return nil
}

func (e SectionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SectionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SectionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Technical/professional skill proficiency — stored in section item metadata.level (SKILLS) and Twin SKILL_AREA.
type SkillLevel string

const (
	SkillLevelBeginner     SkillLevel = "BEGINNER"
	SkillLevelIntermediate SkillLevel = "INTERMEDIATE"
	SkillLevelProficient   SkillLevel = "PROFICIENT"
	SkillLevelAdvanced     SkillLevel = "ADVANCED"
	SkillLevelExpert       SkillLevel = "EXPERT"
)

var AllSkillLevel = []SkillLevel{
	SkillLevelBeginner,
	SkillLevelIntermediate,
	SkillLevelProficient,
	SkillLevelAdvanced,
	SkillLevelExpert,
}

func (e SkillLevel) IsValid() bool {
	switch e {
	case SkillLevelBeginner, SkillLevelIntermediate, SkillLevelProficient, SkillLevelAdvanced, SkillLevelExpert:
		return true
	}
	return false
}

func (e SkillLevel) String() string {
	return string(e)
}

func (e *SkillLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SkillLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SkillLevel", str)
	}
	return nil
}

func (e SkillLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SkillLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SkillLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TwinEntryType string

const (
	TwinEntryTypeExperience TwinEntryType = "EXPERIENCE"
	TwinEntryTypeEducation  TwinEntryType = "EDUCATION"
	TwinEntryTypeProject    TwinEntryType = "PROJECT"
	TwinEntryTypeSkillArea  TwinEntryType = "SKILL_AREA"
	TwinEntryTypeOther      TwinEntryType = "OTHER"
)

var AllTwinEntryType = []TwinEntryType{
	TwinEntryTypeExperience,
	TwinEntryTypeEducation,
	TwinEntryTypeProject,
	TwinEntryTypeSkillArea,
	TwinEntryTypeOther,
}

func (e TwinEntryType) IsValid() bool {
	switch e {
	case TwinEntryTypeExperience, TwinEntryTypeEducation, TwinEntryTypeProject, TwinEntryTypeSkillArea, TwinEntryTypeOther:
		return true
	}
	return false
}

func (e TwinEntryType) String() string {
	return string(e)
}

func (e *TwinEntryType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TwinEntryType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TwinEntryType", str)
	}
	return nil
}

func (e TwinEntryType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TwinEntryType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TwinEntryType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Platform role. ADMIN can manage the knowledge dictionary and view the agent experiment page.
type UserRole string

const (
	UserRoleUser  UserRole = "USER"
	UserRoleAdmin UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleUser,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleUser, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
