package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/leo/ai-weekend/backend/graph/model"
	"github.com/leo/ai-weekend/backend/internal/cv"
	"github.com/leo/ai-weekend/backend/internal/scope"
)

// EffectivePhotoURL is the resolver for the effectivePhotoUrl field.
func (r *contactProfileResolver) EffectivePhotoURL(ctx context.Context, obj *model.ContactProfile) (*string, error) {
	return cv.EffectiveContactPhotoURL(obj), nil
}

// CreateResume is the resolver for the createResume field.
func (r *mutationResolver) CreateResume(ctx context.Context, title string) (*model.Resume, error) {
	return scope.CV(ctx).CreateResume(title), nil
}

// DuplicateResume is the resolver for the duplicateResume field.
func (r *mutationResolver) DuplicateResume(ctx context.Context, id string) (*model.Resume, error) {
	return scope.CV(ctx).DuplicateResume(id)
}

// DeleteResume is the resolver for the deleteResume field.
func (r *mutationResolver) DeleteResume(ctx context.Context, id string) (bool, error) {
	return scope.CV(ctx).DeleteResume(id)
}

// UpdateResume is the resolver for the updateResume field.
func (r *mutationResolver) UpdateResume(ctx context.Context, id string, title *string, contactProfileID *string) (*model.Resume, error) {
	return scope.CV(ctx).UpdateResume(id, title, contactProfileID)
}

// UpdateResumeSettings is the resolver for the updateResumeSettings field.
func (r *mutationResolver) UpdateResumeSettings(ctx context.Context, input model.UpdateResumeSettingsInput) (*model.ResumeSettings, error) {
	return scope.CV(ctx).UpdateResumeSettings(input)
}

// UpdateResumeSectionDisplayTitle is the resolver for the updateResumeSectionDisplayTitle field.
func (r *mutationResolver) UpdateResumeSectionDisplayTitle(ctx context.Context, input model.UpdateResumeSectionDisplayTitleInput) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).UpdateResumeSectionDisplayTitle(input)
}

// ReorderResumeSections is the resolver for the reorderResumeSections field.
func (r *mutationResolver) ReorderResumeSections(ctx context.Context, input model.ReorderResumeSectionsInput) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).ReorderResumeSections(input)
}

// UpdateResumeSectionVisibility is the resolver for the updateResumeSectionVisibility field.
func (r *mutationResolver) UpdateResumeSectionVisibility(ctx context.Context, input model.UpdateResumeSectionVisibilityInput) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).UpdateResumeSectionVisibility(input)
}

// UpdateResumeSectionItemVisibility is the resolver for the updateResumeSectionItemVisibility field.
func (r *mutationResolver) UpdateResumeSectionItemVisibility(ctx context.Context, input model.UpdateResumeSectionItemVisibilityInput) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).UpdateResumeSectionItemVisibility(input)
}

// UpdateResumeSectionItem is the resolver for the updateResumeSectionItem field.
func (r *mutationResolver) UpdateResumeSectionItem(ctx context.Context, input model.UpdateResumeSectionItemInput) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).UpdateResumeSectionItem(input)
}

// AddResumeSectionItem is the resolver for the addResumeSectionItem field.
func (r *mutationResolver) AddResumeSectionItem(ctx context.Context, input model.AddResumeSectionItemInput) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).AddResumeSectionItem(input)
}

// DeleteSectionItem is the resolver for the deleteSectionItem field.
func (r *mutationResolver) DeleteSectionItem(ctx context.Context, resumeID string, sectionItemID string) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).DeleteSectionItem(resumeID, sectionItemID)
}

// UpdateContactProfile is the resolver for the updateContactProfile field.
func (r *mutationResolver) UpdateContactProfile(ctx context.Context, input model.UpdateContactProfileInput) (*model.ResumeWithContent, error) {
	return scope.CV(ctx).UpdateContactProfile(ctx, input)
}

// CreatePortfolio is the resolver for the createPortfolio field.
func (r *mutationResolver) CreatePortfolio(ctx context.Context, title string) (*model.Portfolio, error) {
	return scope.CV(ctx).CreatePortfolio(title), nil
}

// DuplicatePortfolio is the resolver for the duplicatePortfolio field.
func (r *mutationResolver) DuplicatePortfolio(ctx context.Context, id string) (*model.Portfolio, error) {
	return scope.CV(ctx).DuplicatePortfolio(id)
}

// DeletePortfolio is the resolver for the deletePortfolio field.
func (r *mutationResolver) DeletePortfolio(ctx context.Context, id string) (bool, error) {
	return scope.CV(ctx).DeletePortfolio(id)
}

// UpdatePortfolio is the resolver for the updatePortfolio field.
func (r *mutationResolver) UpdatePortfolio(ctx context.Context, id string, title *string, tagline *string, about *string, contactProfileID *string) (*model.Portfolio, error) {
	return scope.CV(ctx).UpdatePortfolio(id, title, tagline, about, contactProfileID)
}

// SetUsername is the resolver for the setUsername field.
func (r *mutationResolver) SetUsername(ctx context.Context, username string) (*model.User, error) {
	svc, err := requireCV(ctx)
	if err != nil {
		return nil, err
	}
	return svc.SetUsername(username)
}

// SetPortfolioSlug is the resolver for the setPortfolioSlug field.
func (r *mutationResolver) SetPortfolioSlug(ctx context.Context, portfolioID string, slug string) (*model.Portfolio, error) {
	svc, err := requireCV(ctx)
	if err != nil {
		return nil, err
	}
	return svc.SetPortfolioSlug(portfolioID, slug)
}

// UpdatePortfolioSettings is the resolver for the updatePortfolioSettings field.
func (r *mutationResolver) UpdatePortfolioSettings(ctx context.Context, input model.UpdatePortfolioSettingsInput) (*model.PortfolioSettings, error) {
	return scope.CV(ctx).UpdatePortfolioSettings(input)
}

// UpdatePortfolioContactProfile is the resolver for the updatePortfolioContactProfile field.
func (r *mutationResolver) UpdatePortfolioContactProfile(ctx context.Context, input model.UpdatePortfolioContactProfileInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).UpdatePortfolioContactProfile(ctx, input)
}

// AddPortfolioProject is the resolver for the addPortfolioProject field.
func (r *mutationResolver) AddPortfolioProject(ctx context.Context, input model.AddPortfolioProjectInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).AddPortfolioProject(input)
}

// UpdatePortfolioProject is the resolver for the updatePortfolioProject field.
func (r *mutationResolver) UpdatePortfolioProject(ctx context.Context, input model.UpdatePortfolioProjectInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).UpdatePortfolioProject(input)
}

// DeletePortfolioProject is the resolver for the deletePortfolioProject field.
func (r *mutationResolver) DeletePortfolioProject(ctx context.Context, portfolioID string, projectID string) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).DeletePortfolioProject(portfolioID, projectID)
}

// SetPortfolioProjectVisibility is the resolver for the setPortfolioProjectVisibility field.
func (r *mutationResolver) SetPortfolioProjectVisibility(ctx context.Context, input model.SetPortfolioProjectVisibilityInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).SetPortfolioProjectVisibility(input)
}

// AddPortfolioSkill is the resolver for the addPortfolioSkill field.
func (r *mutationResolver) AddPortfolioSkill(ctx context.Context, input model.AddPortfolioSkillInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).AddPortfolioSkill(input)
}

// UpdatePortfolioSkill is the resolver for the updatePortfolioSkill field.
func (r *mutationResolver) UpdatePortfolioSkill(ctx context.Context, input model.UpdatePortfolioSkillInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).UpdatePortfolioSkill(input)
}

// DeletePortfolioSkill is the resolver for the deletePortfolioSkill field.
func (r *mutationResolver) DeletePortfolioSkill(ctx context.Context, portfolioID string, skillID string) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).DeletePortfolioSkill(portfolioID, skillID)
}

// AddPortfolioTestimonial is the resolver for the addPortfolioTestimonial field.
func (r *mutationResolver) AddPortfolioTestimonial(ctx context.Context, input model.AddPortfolioTestimonialInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).AddPortfolioTestimonial(input)
}

// UpdatePortfolioTestimonial is the resolver for the updatePortfolioTestimonial field.
func (r *mutationResolver) UpdatePortfolioTestimonial(ctx context.Context, input model.UpdatePortfolioTestimonialInput) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).UpdatePortfolioTestimonial(input)
}

// DeletePortfolioTestimonial is the resolver for the deletePortfolioTestimonial field.
func (r *mutationResolver) DeletePortfolioTestimonial(ctx context.Context, portfolioID string, testimonialID string) (*model.PortfolioWithContent, error) {
	return scope.CV(ctx).DeletePortfolioTestimonial(portfolioID, testimonialID)
}

// RequestProfilePhotoUpload is the resolver for the requestProfilePhotoUpload field.
func (r *mutationResolver) RequestProfilePhotoUpload(ctx context.Context, contentType string, fileName string) (*model.ProfilePhotoUpload, error) {
	return scope.CV(ctx).RequestProfilePhotoUpload(ctx, contentType, fileName)
}

// CreateTwinEntry is the resolver for the createTwinEntry field.
func (r *mutationResolver) CreateTwinEntry(ctx context.Context, input model.CreateTwinEntryInput) (*model.TwinEntry, error) {
	return scope.CV(ctx).CreateTwinEntry(input)
}

// UpdateTwinEntry is the resolver for the updateTwinEntry field.
func (r *mutationResolver) UpdateTwinEntry(ctx context.Context, input model.UpdateTwinEntryInput) (*model.TwinEntry, error) {
	return scope.CV(ctx).UpdateTwinEntry(input)
}

// DeleteTwinEntry is the resolver for the deleteTwinEntry field.
func (r *mutationResolver) DeleteTwinEntry(ctx context.Context, id string) (bool, error) {
	return scope.CV(ctx).DeleteTwinEntry(id)
}

// CreateTrackedJob is the resolver for the createTrackedJob field.
func (r *mutationResolver) CreateTrackedJob(ctx context.Context, url string) (*model.TrackedJob, error) {
	return scope.CV(ctx).CreateTrackedJob(url)
}

// UpdateTrackedJob is the resolver for the updateTrackedJob field.
func (r *mutationResolver) UpdateTrackedJob(ctx context.Context, input model.UpdateTrackedJobInput) (*model.TrackedJob, error) {
	return scope.CV(ctx).UpdateTrackedJob(input)
}

// DeleteTrackedJob is the resolver for the deleteTrackedJob field.
func (r *mutationResolver) DeleteTrackedJob(ctx context.Context, id string) (bool, error) {
	return scope.CV(ctx).DeleteTrackedJob(id)
}

// CreateAssistantThread is the resolver for the createAssistantThread field.
func (r *mutationResolver) CreateAssistantThread(ctx context.Context) (*model.AssistantThread, error) {
	return scope.CV(ctx).CreateAssistantThread()
}

// DeleteAssistantThread is the resolver for the deleteAssistantThread field.
func (r *mutationResolver) DeleteAssistantThread(ctx context.Context, id string) (bool, error) {
	return scope.CV(ctx).DeleteAssistantThread(id)
}

// SendAssistantMessage is the resolver for the sendAssistantMessage field.
func (r *mutationResolver) SendAssistantMessage(ctx context.Context, threadID string, text string, context model.AssistantContextInput, attachments []*model.AssistantAttachmentInput) (*model.AssistantTurnResult, error) {
	return scope.CV(ctx).SendAssistantMessage(ctx, threadID, text, context, attachments)
}

// DisconnectConnection is the resolver for the disconnectConnection field.
func (r *mutationResolver) DisconnectConnection(ctx context.Context, provider model.ConnectionProvider) (bool, error) {
	return scope.CV(ctx).DisconnectConnection(provider)
}

// CreateKnowledgeEntry is the resolver for the createKnowledgeEntry field.
func (r *mutationResolver) CreateKnowledgeEntry(ctx context.Context, input model.CreateKnowledgeEntryInput) (*model.KnowledgeEntry, error) {
	return scope.CV(ctx).CreateKnowledgeEntry(input)
}

// UpdateKnowledgeEntry is the resolver for the updateKnowledgeEntry field.
func (r *mutationResolver) UpdateKnowledgeEntry(ctx context.Context, input model.UpdateKnowledgeEntryInput) (*model.KnowledgeEntry, error) {
	return scope.CV(ctx).UpdateKnowledgeEntry(input)
}

// DeleteKnowledgeEntry is the resolver for the deleteKnowledgeEntry field.
func (r *mutationResolver) DeleteKnowledgeEntry(ctx context.Context, id string) (bool, error) {
	return scope.CV(ctx).DeleteKnowledgeEntry(id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return scope.CV(ctx).Me(), nil
}

// MyWorkspace is the resolver for the myWorkspace field.
func (r *queryResolver) MyWorkspace(ctx context.Context) (*model.Workspace, error) {
	return scope.CV(ctx).MyWorkspace(), nil
}

// WorkspaceStats is the resolver for the workspaceStats field.
func (r *queryResolver) WorkspaceStats(ctx context.Context) (*model.WorkspaceStats, error) {
	return scope.CV(ctx).WorkspaceStats(), nil
}

// Resumes is the resolver for the resumes field.
func (r *queryResolver) Resumes(ctx context.Context) ([]*model.Resume, error) {
	return scope.CV(ctx).ListResumes(), nil
}

// Resume is the resolver for the resume field.
func (r *queryResolver) Resume(ctx context.Context, id string) (*model.Resume, error) {
	resume, err := scope.CV(ctx).GetResume(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return resume, err
}

// Sections is the resolver for the sections field.
func (r *queryResolver) Sections(ctx context.Context, typeArg *model.SectionType) ([]*model.Section, error) {
	return scope.CV(ctx).ListSections(typeArg), nil
}

// Section is the resolver for the section field.
func (r *queryResolver) Section(ctx context.Context, id string) (*model.Section, error) {
	section, err := scope.CV(ctx).GetSection(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return section, err
}

// SectionItems is the resolver for the sectionItems field.
func (r *queryResolver) SectionItems(ctx context.Context, typeArg *model.SectionType) ([]*model.SectionItem, error) {
	return scope.CV(ctx).ListSectionItems(typeArg), nil
}

// SectionItem is the resolver for the sectionItem field.
func (r *queryResolver) SectionItem(ctx context.Context, id string) (*model.SectionItem, error) {
	item, err := scope.CV(ctx).GetSectionItem(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return item, err
}

// ContactProfiles is the resolver for the contactProfiles field.
func (r *queryResolver) ContactProfiles(ctx context.Context) ([]*model.ContactProfile, error) {
	return scope.CV(ctx).ListContactProfiles(), nil
}

// CvThemes is the resolver for the cvThemes field.
func (r *queryResolver) CvThemes(ctx context.Context) ([]*model.CvTheme, error) {
	return scope.CV(ctx).ListCvThemes(), nil
}

// ResumeWithContent is the resolver for the resumeWithContent field.
func (r *queryResolver) ResumeWithContent(ctx context.Context, id string) (*model.ResumeWithContent, error) {
	content, err := scope.CV(ctx).GetResumeWithContent(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return content, err
}

// Portfolios is the resolver for the portfolios field.
func (r *queryResolver) Portfolios(ctx context.Context) ([]*model.Portfolio, error) {
	return scope.CV(ctx).ListPortfolios(), nil
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context, id string) (*model.Portfolio, error) {
	portfolio, err := scope.CV(ctx).GetPortfolio(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return portfolio, err
}

// PortfolioWithContent is the resolver for the portfolioWithContent field.
func (r *queryResolver) PortfolioWithContent(ctx context.Context, id string) (*model.PortfolioWithContent, error) {
	content, err := scope.CV(ctx).GetPortfolioWithContent(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return content, err
}

// PublicPortfolioWithContent is the resolver for the publicPortfolioWithContent field.
func (r *queryResolver) PublicPortfolioWithContent(ctx context.Context, username string, slug *string) (*model.PortfolioWithContent, error) {
	pg := scope.Postgres(ctx)
	if pg == nil {
		return nil, fmt.Errorf("not available")
	}
	content, err := pg.PublicPortfolioWithContent(username, slug)
	if err != nil {
		return nil, err
	}
	return content, nil
}

// SectionItemUsage is the resolver for the sectionItemUsage field.
func (r *queryResolver) SectionItemUsage(ctx context.Context, id string) (*model.SectionItemUsage, error) {
	usage, err := scope.CV(ctx).GetSectionItemUsage(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return usage, err
}

// SectionItemsForSection is the resolver for the sectionItemsForSection field.
func (r *queryResolver) SectionItemsForSection(ctx context.Context, sectionID string) ([]*model.SectionItem, error) {
	items, err := scope.CV(ctx).SectionItemsForSection(sectionID)
	if cv.NotFound(err) {
		return nil, nil
	}
	return items, err
}

// ResumesForSection is the resolver for the resumesForSection field.
func (r *queryResolver) ResumesForSection(ctx context.Context, sectionID string) ([]*model.Resume, error) {
	resumes, err := scope.CV(ctx).ResumesForSection(sectionID)
	if cv.NotFound(err) {
		return nil, nil
	}
	return resumes, err
}

// AssistantThreads is the resolver for the assistantThreads field.
func (r *queryResolver) AssistantThreads(ctx context.Context) ([]*model.AssistantThread, error) {
	return scope.CV(ctx).ListAssistantThreads(), nil
}

// AssistantMessages is the resolver for the assistantMessages field.
func (r *queryResolver) AssistantMessages(ctx context.Context, threadID string, limit *int) ([]*model.AssistantMessage, error) {
	l := 50
	if limit != nil {
		l = *limit
	}
	return scope.CV(ctx).ListAssistantMessages(threadID, l), nil
}

// TwinEntries is the resolver for the twinEntries field.
func (r *queryResolver) TwinEntries(ctx context.Context) ([]*model.TwinEntry, error) {
	return scope.CV(ctx).ListTwinEntries(), nil
}

// TwinEntry is the resolver for the twinEntry field.
func (r *queryResolver) TwinEntry(ctx context.Context, id string) (*model.TwinEntry, error) {
	entry, err := scope.CV(ctx).GetTwinEntry(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return entry, err
}

// TrackedJobs is the resolver for the trackedJobs field.
func (r *queryResolver) TrackedJobs(ctx context.Context) ([]*model.TrackedJob, error) {
	return scope.CV(ctx).ListTrackedJobs(), nil
}

// TrackedJob is the resolver for the trackedJob field.
func (r *queryResolver) TrackedJob(ctx context.Context, id string) (*model.TrackedJob, error) {
	job, err := scope.CV(ctx).GetTrackedJob(id)
	if cv.NotFound(err) {
		return nil, nil
	}
	return job, err
}

// ConnectionStatus is the resolver for the connectionStatus field.
func (r *queryResolver) ConnectionStatus(ctx context.Context, provider model.ConnectionProvider) (*model.ConnectionStatus, error) {
	return scope.CV(ctx).ConnectionStatus(provider)
}

// KnowledgeEntries is the resolver for the knowledgeEntries field.
func (r *queryResolver) KnowledgeEntries(ctx context.Context, includeDisabled *bool) ([]*model.KnowledgeEntry, error) {
	include := true
	if includeDisabled != nil {
		include = *includeDisabled
	}
	return scope.CV(ctx).ListKnowledgeEntries(include)
}

// ClassifyAssistantMessage is the resolver for the classifyAssistantMessage field.
func (r *queryResolver) ClassifyAssistantMessage(ctx context.Context, text string, context model.AssistantContextInput) (*model.AssistantClassification, error) {
	return scope.CV(ctx).ClassifyAssistantMessage(ctx, text, context)
}

// ContactProfile returns ContactProfileResolver implementation.
func (r *Resolver) ContactProfile() ContactProfileResolver { return &contactProfileResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type contactProfileResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
