import type { TrackedJob } from "@/lib/types/job";

export const DEMO_TRACKED_JOBS: TrackedJob[] = [
  {
    id: "demo-linear",
    workspaceId: "demo",
    url: "https://linear.app/careers/senior-frontend-engineer",
    title: "Senior Frontend Engineer",
    company: "Linear",
    status: "SAVED",
    notes: "",
    resumeId: "demo-cv-1",
    coverLetter: "",
    metadata: {},
    createdBy: "demo",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "demo-openai",
    workspaceId: "demo",
    url: "https://openai.com/careers/ml-engineer",
    title: "Machine Learning Engineer",
    company: "OpenAI",
    status: "APPLIED",
    notes: "",
    resumeId: "demo-cv-2",
    coverLetter: "Tailored cover letter",
    metadata: {},
    createdBy: "demo",
    createdAt: "2026-01-02T00:00:00.000Z",
    updatedAt: "2026-01-02T00:00:00.000Z",
  },
  {
    id: "demo-figma",
    workspaceId: "demo",
    url: "https://figma.com/careers/product-designer",
    title: "Product Designer",
    company: "Figma",
    status: "APPLIED",
    notes: "",
    resumeId: "demo-cv-3",
    coverLetter: "",
    metadata: {},
    createdBy: "demo",
    createdAt: "2026-01-03T00:00:00.000Z",
    updatedAt: "2026-01-03T00:00:00.000Z",
  },
  {
    id: "demo-stripe",
    workspaceId: "demo",
    url: "https://stripe.com/jobs/staff-engineer",
    title: "Staff Engineer",
    company: "Stripe",
    status: "INTERVIEW",
    notes: "",
    resumeId: "demo-cv-4",
    coverLetter: "Tailored cover letter",
    metadata: {},
    createdBy: "demo",
    createdAt: "2026-01-04T00:00:00.000Z",
    updatedAt: "2026-01-04T00:00:00.000Z",
  },
  {
    id: "demo-startup",
    workspaceId: "demo",
    url: "https://example.com/jobs/founding-engineer",
    title: "Founding Engineer",
    company: "Seed-stage startup",
    status: "OFFER",
    notes: "",
    resumeId: "demo-cv-5",
    coverLetter: "",
    metadata: {},
    createdBy: "demo",
    createdAt: "2026-01-05T00:00:00.000Z",
    updatedAt: "2026-01-05T00:00:00.000Z",
  },
];
